// Subtask 1.1 — Interface Topic16Data
export interface ParadoxMetric {
	value: string;
	label: string;
	color: 'positive' | 'negative';
}

export interface RiskFinding {
	text: string;
	type: 'scan' | 'alert';
}

export interface EnterpriseCard {
	company: string;
	stat: string;
	detail: string;
}

export interface LoopStep {
	phase: 'specs' | 'generate' | 'review' | 'human';
	label: string;
	items: string[];
	note: string;
}

export interface Topic16Data {
	title: string;
	subtitle: string;
	paradox: {
		eyebrow: string;
		headline: string;
		metrics: ParadoxMetric[];
		subMetrics: string;
		implication: string;
	};
	riskFindings: RiskFinding[];
	enterpriseConsensus: string;
	enterpriseCards: EnterpriseCard[];
	loopSteps: LoopStep[];
	loopNote: string;
	finalManifesto: {
		lines: string[];
		quote: string;
		source: string;
	};
	narratorNotes: string[];
	labels: {
		paradoxEyebrow: string;
		riskEyebrow: string;
		enterpriseEyebrow: string;
		loopEyebrow: string;
		manifestoEyebrow: string;
		notesTerminalTitle: string;
		notesTerminalLead: string;
		notesLinePrefix: string;
		notesTerminalOutro: string;
	};
}

// Subtask 1.2 & 1.3 — Dados de topic16.md, estruturados nos 4 momentos visuais
export const topic16Data: Topic16Data = {
	title: 'O Gargalo Mudou',
	subtitle: 'E a resposta já foi dada.',

	paradox: {
		eyebrow: 'O Paradoxo de 2026 · Faros AI — 10.000+ devs',
		headline: 'IA gera código 98% mais rápido. O tempo de review aumentou 91%.',
		metrics: [
			{ value: '+98%', label: 'mais PRs por semana', color: 'positive' },
			{ value: '+91%', label: 'mais tempo de review', color: 'negative' },
		],
		subMetrics: '+154% tamanho de PR · +9% bugs por dev',
		implication:
			'O bottleneck não é mais escrever código. É entender código. E quando 45% do código gerado por IA tem falhas de segurança, entender virou uma questão de sobrevivência.',
	},

	riskFindings: [
		{ text: 'AI-generated code: 45% security flaws', type: 'alert' },
		{ text: 'XSS vulnerabilities: 2.74× higher in AI PRs', type: 'scan' },
		{ text: 'AI PRs: 1.7× more defects than human PRs', type: 'scan' },
		{ text: 'Hallucinated packages: 19.7% of 576K samples', type: 'alert' },
		{ text: 'Best model correct + secure: only 38%', type: 'scan' },
		{ text: 'Fortune 50: 4× velocity, 10× security findings/month', type: 'alert' },
		{ text: 'Java generated by AI: 72% security failure rate', type: 'alert' },
	],

	enterpriseConsensus: 'Trate código de IA como código de terceiro não confiável.',
	enterpriseCards: [
		{
			company: 'GOOGLE',
			stat: '30%+ do código de produção é IA',
			detail: 'Review humano obrigatório — diretriz interna jun/2025',
		},
		{
			company: 'STRIPE',
			stat: '1.300+ PRs/semana 100% escritos por IA',
			detail: 'Todo PR revisado por humano, sem exceção',
		},
		{
			company: 'UBER',
			stat: '90% dos 65.000 diffs/semana com AI review',
			detail: '75% dos comentários marcados como úteis pelos engenheiros',
		},
		{
			company: 'SHOPIFY',
			stat: 'Entrevistas avaliam: encontrar erros em código de IA',
			detail: 'Meta: 90-95% IA — e capacidade de inspecionar os outros 5%',
		},
	],

	loopSteps: [
		{
			phase: 'specs',
			label: 'SPECS (upstream)',
			items: ['Spec-Kit', 'GSD', 'BMAD'],
			note: 'Governa o que será gerado',
		},
		{
			phase: 'generate',
			label: 'IA GERA CÓDIGO',
			items: [],
			note: 'Código gerado com contexto limpo',
		},
		{
			phase: 'review',
			label: 'REVIEW (downstream)',
			items: ['Copilot Code Review', 'CodeRabbit', 'SonarQube', 'Claude Code Security'],
			note: 'Examina o que foi escrito',
		},
		{
			phase: 'human',
			label: 'HUMANO APROVA',
			items: [],
			note: 'Decisão final — inegociável',
		},
	],
	loopNote: 'Specs upstream + review downstream. Um sem o outro é incompleto.',

	finalManifesto: {
		lines: ['Especificar antes.', 'Revisar depois.', 'Entender sempre.'],
		quote: '"IA não conserta um time. Ela amplifica o que já existe."',
		source: 'DORA Report 2025 — ~5.000 profissionais de engenharia',
	},

	narratorNotes: [
		'Abertura: o paradoxo 98% vs 91% é o gancho — times com mais IA fazem mais PRs, mas gastam quase o dobro revisando. Deixe o número impactar.',
		'Os Números: 45% do código de IA com falhas de segurança. PRs 1.7× mais defeituosos. Slopsquatting: 19.7% dos pacotes recomendados não existem — vetor de ataque novo.',
		'Os Grandes: Google, Stripe, Uber, Shopify — não são experimentos, são as empresas que MAIS usam IA. E o padrão é o mesmo: todo código de IA é revisado por humano.',
		'A Conexão: specs upstream (Spec-Kit, GSD, BMAD) + review downstream. As ferramentas dos Tópicos 7-9 são o primeiro filtro — governam o que será gerado.',
		'Fechamento: DORA 2025 com 5.000 profissionais: "IA não conserta um time. Ela amplifica o que já existe." Pausa antes. Pausa depois. Não termine pedindo nada — deixe o silêncio trabalhar.',
	],

	labels: {
		paradoxEyebrow: 'Momento 1 — O Paradoxo',
		riskEyebrow: 'Momento 2 — A Parede de Dados',
		enterpriseEyebrow: 'Momento 3 — O Padrão dos Grandes',
		loopEyebrow: 'Momento 4 — O Loop Fechado',
		manifestoEyebrow: 'Encerramento',
		notesTerminalTitle: 'narrator://topic16',
		notesTerminalLead: 'Condução sugerida — O Gargalo Mudou (CTA Final, ~4-5 min).',
		notesLinePrefix: 'nota',
		notesTerminalOutro: 'Fecho: "Especificar antes. Revisar depois. Entender sempre."',
	},
};
